-- Insert dummy projects
INSERT INTO projects (project_id, name, description, owner_id, repository_url, branch, docker_compose_path, project_status, created_date, updated_date)
VALUES
    (gen_random_uuid(),
     'E-Commerce Platform',
     'Full-stack e-commerce application with React frontend and Spring Boot backend',
     'user-123',
     'https://github.com/example/ecommerce-platform',
     'main',
     '/docker/docker-compose.yml',
     'ACTIVE',
     CURRENT_TIMESTAMP,
     CURRENT_TIMESTAMP),

    (gen_random_uuid(),
     'Analytics Dashboard',
     'Real-time analytics dashboard for monitoring application metrics',
     'user-123',
     'https://github.com/example/analytics-dashboard',
     'develop',
     '/deployment/docker-compose.yml',
     'ACTIVE',
     CURRENT_TIMESTAMP - INTERVAL '5 days',
     CURRENT_TIMESTAMP - INTERVAL '2 days'),

    (gen_random_uuid(),
     'Task Management System',
     'Collaborative task management tool with team features',
     'user-456',
     'https://github.com/example/task-manager',
     'main',
     '/docker-compose.yml',
     'PENDING',
     CURRENT_TIMESTAMP - INTERVAL '10 days',
     CURRENT_TIMESTAMP - INTERVAL '3 days'),

    (gen_random_uuid(),
     'Payment Gateway Integration',
     'Microservice for handling payment processing and transactions',
     'user-789',
     'https://github.com/example/payment-service',
     'feature/stripe-integration',
     '/infra/docker-compose.yml',
     'FAILED',
     CURRENT_TIMESTAMP - INTERVAL '15 days',
     CURRENT_TIMESTAMP - INTERVAL '1 day'),

    (gen_random_uuid(),
     'Authentication Service',
     'OAuth2 and JWT-based authentication microservice',
     'user-456',
     'https://github.com/example/auth-service',
     'main',
     '/docker/docker-compose.prod.yml',
     'ACTIVE',
     CURRENT_TIMESTAMP - INTERVAL '30 days',
     CURRENT_TIMESTAMP - INTERVAL '5 days');